Initial pass at pulling in Gatsby capabilities (#1778)
This is a first pass at getting Gatsby available on the docs site, which will allow us to begin migrating content over. See the additions to README.md for an understanding of how this works.

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -6,10 +6,13 @@
 set -e
 
 # Install Homebrew
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if ! [ -x $(command -v homebrew) ]; then
+    echo "Homebrew not found, initializing installation"
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+fi
 
-# Install dependencies
-brew install ruby node yarn
-gem install bundler
+# Install system toolchain
+brew install ruby volta
 
-# We don't need to run bundler or yarn, bin/server handles that.
+# App dependencies
+make
